### ISSUE TITLE
OpenCV installation problems on Yosemite

### ISSUE THREAD

**Issue by lanbau** [alyssaq/python-data-science-intro#1]
Hi alyssa! thanks for the instructions.

I couldn't get opencv3 to install on mac -  yosemite v10.10.5. The issue i had was no module cv2 was found.

Found a solution that finally works after hours of searching on Google. 

https://ceciliavision.wordpress.com/2014/10/28/installing-opencv-2-4-10-on-yosemite/

Just wanted to share with the rest.

Thanks!
Irvin

**Comment by alyssaq** [comment]
Hi Irvin

Im glad you finally got it installed. :)

I personally use (and prefer) homebrew and dont use macports.  
If anyone wants to install opencv 2.4.x with homebrew, I have an older post: http://alyssaq.github.io/2014/installing-opencv-on-mac-osx-with-homebrew/

OpenCV 3.0 uses the same module namespace cv2. 

Alyssa

**Comment by lanbau** [comment]
Hey alyssa thanks!

upgraded my os to el capitan..

ran into this problem while running this command: 
pip3 install git+git://github.com/statsmodels/statsmodels

Here's the stack trace...

```
Collecting git+git://github.com/statsmodels/statsmodels
  Cloning git://github.com/statsmodels/statsmodels to /var/folders/6z/8tmsrhwj1n1f00hjt009x3mm0000gn/T/pip-jz5c1kct-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/var/folders/6z/8tmsrhwj1n1f00hjt009x3mm0000gn/T/pip-jz5c1kct-build/setup.py", line 401, in <module>
        install_requires) = check_dependency_versions(min_versions)
      File "/var/folders/6z/8tmsrhwj1n1f00hjt009x3mm0000gn/T/pip-jz5c1kct-build/setup.py", line 137, in check_dependency_versions
        from pandas import __version__ as pversion
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/__init__.py", line 44, in <module>
        from pandas.core.api import *
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/core/api.py", line 9, in <module>
        from pandas.core.groupby import Grouper
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/core/groupby.py", line 17, in <module>
        from pandas.core.frame import DataFrame
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/core/frame.py", line 41, in <module>
        from pandas.core.series import Series
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/core/series.py", line 2909, in <module>
        import pandas.tools.plotting as _gfx
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/tools/plotting.py", line 28, in <module>
        import pandas.tseries.converter as conv
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/tseries/converter.py", line 7, in <module>
        import matplotlib.units as units
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/__init__.py", line 1131, in <module>
        rcParams = rc_params()
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/__init__.py", line 975, in rc_params
        return rc_params_from_file(fname, fail_on_error)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/__init__.py", line 1100, in rc_params_from_file
        config_from_file = _rc_params_in_file(fname, fail_on_error)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
        with _open_file_or_url(fname) as fd:
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 59, in __enter__
        return next(self.gen)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/__init__.py", line 1000, in _open_file_or_url
        encoding = locale.getdefaultlocale()[1]
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/locale.py", line 559, in getdefaultlocale
        return _parse_localename(localename)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/locale.py", line 487, in _parse_localename
        raise ValueError('unknown locale: %s' % localename)
    ValueError: unknown locale: UTF-8

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /var/folders/6z/8tmsrhwj1n1f00hjt009x3mm0000gn/T/pip-jz5c1kct-build
```

**Comment by alyssaq** [comment]
I think you're missing the locale environment variable:

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

I've updated the [installation gist](export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8)

**Comment by lanbau** [comment]
cool. that works. I'm having another problem with installing opencv3 
i ran the commands 

```
$ brew tap homebrew/science
$ brew update && brew install opencv3 --with-contrib --with-python3
$ echo /usr/local/opt/opencv3/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/opencv3.pth
$ ln -s /usr/local/opt/opencv3/lib/python3.5/site-packages/cv2.cpython-35m-darwin.so /usr/local/lib/python3.5/site-packages/cv2.so
```

But python3 gave me this 

```
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'cv2'
```
- I tried using symlink according to your blogpost but it's still giving me the no module error.
  Here is the command i ran 

```
lanbaus-MBP:~ lanbau$ brew link --overwrite opencv3 --force
Linking /usr/local/Cellar/opencv3/3.1.0... 131 symlinks created
```

Not sure if i messed it up. haha. thanks for the help on xmas eve!

**Comment by lanbau** [comment]
Fixed it! according to this website, it seems i needed to set PYTHONPATH to

```
export PYTHONPATH=$PYTHONPATH:/usr/local/Cellar/opencv3/3.1.0/lib/python3.5/site-packages
```

in my bash_profile.

Thanks
Irvin

source: http://webcache.googleusercontent.com/search?q=cache:mgo_BRf9jpcJ:tsaith.github.io/blog/2015/08/31/install-opencv-3-for-python-3-on-osx+&cd=1&hl=en&ct=clnk&gl=sg
